name: releases
on:
  push:
    tags:
      - "v*"
jobs:
  release-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: damillora/phoebe
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}
      - name: Build and push
        id: docker_build_git
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  binaries:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.goreleaser.outputs.metadata }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - id: goreleaser
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_CODENAME: ${{ vars.RELEASE_CODENAME }}
          RELEASE_SUBTITLE: ${{ vars.RELEASE_SUBTITLE }}
          RELEASE_QUOTE: ${{ vars.RELEASE_QUOTE }}
